// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aullweizxcjbvtdspjli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1bGx3ZWl6eGNqYnZ0ZHNwamxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyNjM0MzQsImV4cCI6MjA5MTgzOTQzNH0.51GHwshenJSgaB8WeckVojfsQGVtuN4sfTbY_b0CbE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});